// Generated by CoffeeScript 1.4.0
(function() {
  var Memorable;

  Memorable = (function() {

    Memorable.prototype.Key = "";

    Memorable.prototype.Data = {};

    Memorable.prototype.Time = new Date();

    Memorable.prototype.Invalid = false;

    Memorable.prototype.Size = 0;

    Memorable.prototype.Expires = 0;

    function Memorable(key, data, options) {
      var _ref;
      if (typeof key === 'undefined') {
        throw "Memorable missing key element";
      }
      if (typeof data === 'undefined') {
        throw "Memorable missing data element";
      }
      if (options == null) {
        options = {};
      }
      if ((_ref = options.maxAge) == null) {
        options.maxAge = 0;
      }
      this.Key = key;
      this.Data = data;
      if (maxAge !== 0) {
        this.Expires = this.Time.now + (maxAge * 1000);
      }
      this.Size = this.CalculateSize();
    }

    Memorable.prototype.IsExpired = function() {
      return this.Expires === 0 || this.Time.now < this.Expires;
    };

    Memorable.prototype.Invalidate = function() {
      return this.Invalid = true;
    };

    Memorable.prototype.CalculateSize = function() {
      var bytes, check, clearFuncs, func, isChecked, stack, uncheck, value;
      clearFuncs = [];
      stack = [this.heap];
      bytes = 0;
      func = null;
      isChecked = function(item) {
        return item["__c"] || false;
      };
      check = function(item) {
        return item["__c"] = true;
      };
      uncheck = function(item) {
        return delete item["__c"];
      };
      while (stack.length) {
        value = stack.pop();
        (function(value) {
          var i, val;
          if (typeof value === 'string') {
            return bytes += value.length * 2;
          } else if (typeof value === 'boolean') {
            return bytes += 4;
          } else if (typeof value === 'number') {
            return bytes += 8;
          } else if (typeof value === 'object' && !isChecked(value)) {
            clearFuncs.push(function() {
              return uncheck(value);
            });
            for (i in value) {
              val = value[i];
              if (value.hasOwnProperty(i)) {
                stack.push(val);
              }
            }
            return check(value);
          }
        })(value);
      }
      while (func = clearFuncs.pop()) {
        func.call();
      }
      return bytes;
    };

    return Memorable;

  })();

  module.exports = Memorable;

}).call(this);
