// Generated by CoffeeScript 1.4.0
(function() {
  var Memorable;

  Memorable = (function() {

    Memorable.prototype.Key = "";

    Memorable.prototype.Data = {};

    Memorable.prototype.Time = new Date();

    Memorable.prototype.Invalid = false;

    Memorable.prototype.Expires = 0;

    function Memorable(key, data, options) {
      var _ref;
      if (typeof key === 'undefined') {
        throw "Memorable missing key element";
      }
      if (typeof data === 'undefined') {
        throw "Memorable missing data element";
      }
      if (options == null) {
        options = {};
      }
      if ((_ref = options.maxAge) == null) {
        options.maxAge = 0;
      }
      this.Key = key;
      this.Data = data;
      if (maxAge !== 0) {
        this.Expires = this.Time.now + (maxAge * 1000);
      }
    }

    Memorable.prototype.IsExpired = function() {
      return this.Expires === 0 || this.Time.now < this.Expires;
    };

    Invalidate(function() {
      return this.Invalid = true;
    });

    return Memorable;

  })();

  module.exports = Memorable;

}).call(this);
